spring:
  banner:
    location: classpath:ascii-art.txt
  datasource:
    url: jdbc:postgresql://${DB_ADDRESS}:${DB_PORT}/${DB_NAME}?reWriteBatchedInserts=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 120000
      connectionTimeout: 300000
      leakDetectionThreshold: 1800000
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        # show_sql: true
        jdbc:
          time_zone: UTC
          batch_size: 100
        order_updates: true
        order_inserts: true
        batch_versioned_data: true
        default_batch_fetch_size: 100
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
  json:
    trusted:
      packages: "org.exchange.app.common.api, org.exchange.app.external.api"
    value:
      userTicket:
        type: org.exchange.app.common.api.model.UserTicket
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: external-backend
          client-secret: ${KEYCLOAK_CLIENT_SECRET}
          introspection-uri: ${exchange-portal.security.keycloak.url}/realms/exchange-realm/protocol/openid-connect/token/introspect

exchange-portal:
  security:
    active: true
    keycloak:
      url: ${KEYCLOAK_URL}
      active: true
  allowed-origins:
    http://localhost:4100 http://localhost:8080 http://localhost:8002

server:
  error:
    include-message: always
  port: 8002

exchange:
  strategy:
    ratio: ${EXCHANGE_RATIO_STRATEGY}
    fee: ${EXCHANGE_FEE_STRATEGY}
management:
  endpoints:
    web:
      exposure:
        include: '*'
springdoc:
  show-actuator: true